"""empty message

Revision ID: 2a9434480985
Revises: 8737745d3c63
Create Date: 2020-11-06 00:52:48.279805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a9434480985'
down_revision = '8737745d3c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('user_from_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_to_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['user.id'], name='followers_ibfk_1'),
    sa.ForeignKeyConstraint(['user_to_id'], ['user.id'], name='followers_ibfk_2'),
    sa.PrimaryKeyConstraint('user_from_id', 'user_to_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
